/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Current multiplier :": "当前乘数：",
    "Current DP/s :": "当前 DP/秒：",
    "... And all for one": "... 一切为了一个",
    "Makes Negative Point generation stronger": "使负点数生成更强",
    "Makes Negative power generation stronger": "让负能量更强大",
    "Max All": "全部最大",
    "Max All Button": "全部最大按钮",
    "Minecraft not included": "不包括我的世界",
    "Need 1e10 DP": "需要 1e10 DP",
    "Need at least 1 of each other C": "彼此至少需要 1 个 C",
    "Negative Prestige": "负声望",
    "Nine only": "只有9",
    "Nine Only : try to get only 9 C9 and 9 C-9": "仅九个：尝试仅获得 9 个 C9 和 9 个 C-9",
    "NP multiplies DP by 0.1log(NP+1) (Additive)": "NP 将 DP 乘以 0.1log(NP+1)（加法）",
    "NP multiplies DP production by 0.4log(NP+1) (additive)": "NP 将 DP 产量乘以 0.4log(NP+1)（加法）",
    "NP multiplies DP productions by 0.3log(NP+1) (Additive)": "NP 将 DP 产生乘以 0.3log(NP+1)（加法）",
    "nullifiers. (this is the number of C0 you have minus the number of skills you already bought)": "无效符。 （这是你拥有的C0数量减去你已经购买的技能数量）",
    "One for all...": "一个为所有...",
    "Get to an higher dimension": "到达更高的维度",
    "Halves Quality requirement scaling (applies retroactively)": "质量要求缩放减半（追溯适用）",
    "Hard Reset": "硬重置",
    "Help": "帮助",
    "Help tab": "帮助选项卡",
    "Here is a link to the video from": "这是视频的链接",
    "I'll, one day, add links to other stuff related to Fourrier series that i made so you can have fun with greater values of n.": "有一天，我会添加与我制作的 Fourrier 系列相关的其他内容的链接，这样您就可以享受更大的 n 值。",
    "I've also given you back all the sliders! if they are locked again, just click on that button again!": "我还给了你所有的滑块！ 如果它们再次被锁定，只需再次单击该按钮！",
    "Improve distance multiplier": "提高距离乘数",
    "Improve Distance Multiplier": "提高距离乘数",
    "Improve quality": "提高质量",
    "  Your browser does not support the audio element.\n": "您的浏览器不支持音频元素。\n",
    "Fourier found that for any 2D shape that is continuous (you can draw it without having to lift the pen once) and have the starting point and the end point that are the same, there was a complex function that can draw it for t between 0 and 1 :": "傅里叶发现，对于任意连续的二维形状(你可以画出它而不需要举起笔一次)，并且起点和终点是相同的，有一个复杂的函数可以画出t在0到1之间的形状:",
    "Enable Autobuy": "启用自动购买",
    "Enable Autosave": "启用自动保存",
    "F is for Fibonacci!": "F代表斐波那契！",
    "Fermat's little importation": "费马的小输入",
    "Fourier Incremental": "傅里叶增量",
    "Reset Skill Tree": "重置技能树",
    "Resets everything except the achievements (and what they unlock)": "重置除成就以外的所有内容（以及他们解锁的内容）",
    "Resets everything, even the achievements": "重置一切，甚至成就",
    "Same logic for BAGUETTE": "和 法国面包 的逻辑相同",
    "Secret get!": "秘密获得！",
    "Show the construction vector in green (what each Cn does)": "以绿色显示构造向量（每个 Cn 的作用）",
    "Skill Tree": "技能树",
    "So, that wasn't how stuff were supposed to happen, but here is a link to the discord server of the game :": "所以，这不是事情应该发生的方式，但这里是游戏不和谐服务器的链接：",
    "Soft Reset": "软重置",
    "Increase distance multiplier": "增加距离乘数",
    "Increase the distance multiplier": "增加距离乘数",
    "Increase tick rate by 10%": "将tick速率提高 10%",
    "increment": "增量",
    "is a list of angles in radians": "是以弧度为单位的角度列表",
    "is a list of positive reals (take it as a list of radius) and": "是一个正实数列表（将其作为半径列表）和",
    "Disable that horrible sound (working on it, the button doesn't work yet)": "禁用那个可怕的声音（正在处理它，按钮还不起作用）",
    "Devil's number": "恶魔号码",
    "Each negative Cn (except for C-1) increase the Cn before it on a fictive way, that does count for the increase of the next one etc, then C-1 and fictive C-1 increase the negative product that multiplies DP production": "每一个负的Cn(除了C-1)以一种虚拟的方式增加它前面的Cn，这确实可以计算下一个的增加等，然后C-1和虚拟的C-1增加负的乘积，乘以DP产量",
    "This is the end of the game, if you want you can go to the discord server to have fun with the bot or if you want to have news about my other current project (a Puzzle-RPG), but don't forget to do the verification or you won't have access to anything!": "这是游戏的结束，如果你想，你可以去 discord 服务器有乐趣与机器人或如果你想有关于我的其他当前项目(一个谜rpg)的消息，但不要忘记做验证，否则你将没有访问任何东西!",
    "The precedent skill applies to achievements": "先例技能适用于成就",
    "The server is pretty empty and the main purpose of it was not to be about that incremental game, but a RPG that i'm programming. Still, it has a Fourier bot you can mess with!": "服务器非常空旷，它的主要目的不是关于那个增量游戏，而是我正在编程的 RPG。 不过，它有一个傅里叶机器人，你可以搞砸！",
    "There is a factor that added to 1, multiplies DP production. It grows with negative Cns": "有一个因素加到 1 上，使 DP 产量倍增。 它以负 Cns 生长",
    "There is a factor that multiplies DP production : it represent the scaling of the drawing, it resets on prestige (any), the skills related to it makes it squared if you have 1, cubed if you have 2 etc": "有一个因素可以使 DP 产生倍增：它代表绘图的缩放比例，它在声望（任何）上重置，与它相关的技能如果你有 1 则使其平方，如果你有 2 则立方等",
    "There is no point in doing that...(prestige without any quality upgrade)": "这样做是没有意义的......（没有任何质量升级的声望）",
    "This whole game is about the Fourier series (not the transform!) and this tab will explain to you what all this is about.": "整个游戏都是关于傅里叶级数（不是变换！），这个标签会向你解释这一切是关于什么的。",
    "to show you how powerful this tool is (and explain it better than i do)": "向您展示此工具的强大功能（并比我解释得更好）",
    "Value:": "价值：",
    "Wait, did you said \"Reduce\" ?": "等等，你说的是“减少”吗？",
    "Where": "在哪里",
    "Yes, i'm a furry": "是的，我是福瑞",
    "You currently have": "你目前有",
    "\"... and all for one\" requires you to prestige with only C1, no other positive Cn": "\"... 多对一\" 要求你只有 C1 声望，没有其他正 Cn",
    "\"One for all...\" requires you to have simultaneously 1 of each Cn (positive and negative, not counting C0)": "\"一对多...\" 要求您同时拥有每个 Cn 中的 1 个（正负，不包括 C0）",
    "\"Synergize\" means that they increase each other's strength, it's calculated by adding the base 10 logarithm of one's value and adding a portion of it to the power of the multiplier they already have (which is 1)": "\"协同\"的意思是他们互相增加了对方的实力，它是通过将一个人的价值以10为底的对数相加，并将其中的一部分加上他们已经拥有的乘数的幂（即1）来计算的",
    "A little link to something i made with those series and python :": "我用这些系列和 python 制作的东西的一个小链接：",
    "A slice of Pi": "一片 Pi",
    "A slice of Pi is : 3.141592653... 1 digit is one Cn, from C1 to C10, you can have any negative Cn.": "一片 Pi 是：3.141592653... 1 位是一个 Cn，从 C1 到 C10，你可以有任何负 Cn。",
    "About": "关于",
    "About+": "关于+",
    "Achievements are currently being worked on!": "目前正在取得成就！",
    "Achievements can unlock features and will multiply your DP production by": "成就可以解锁功能，并将您的 DP 产量增加",
    "Actually clicks 10 times on each button except prestiges": "除了声望之外，每个按钮实际上点击了 10 次",
    "Ah yes, it really reduces it...": "啊，是的，它确实减少了它......",
    "Autobuys Quality Upgrade once each tick": "自动购买质量升级一次",
    "Autobuys tickspeed once each tick": "每次滴答自动购买滴答速度",
    "Autosaves each 10 seconds, can be disabled by getting skilled": "每 10 秒自动保存一次，熟练后可以禁用",
    "BAGUETTE!": "法国面包！",
    "BREAD": "面包",
    "Change the base 10 logarithms in the skills to base 2": "将技能中以10为底的对数改为以2为底",
    "Click me! i'm innoffensive": "点我！我无害",
    "Click on me once you have all skills and at least 100 C0 to unlock a new dimension!": "一旦你拥有所有技能并且至少有 100 个 C0，请点击我来解锁一个新的维度！",
    "Main": "首页",
    "Prestige for": "声望获得",
    "Prestige Down": "声望降低",
    "Stuck (Have 5 quality upgrades without any positive or negative Cn)": "卡住（有 5 次质量升级，没有任何正面或负面的 Cn）",
    "The achievement Row 6 column 2 requires you to draw a \"Lemniscate\" (the infinity symbol), this can be done by having 1 of C2 and C-2 and 2 of C1 and C-1, then playing with angles.": "成就第 6 行第 2 列要求你画一个“Lemniscate”（无限的符号），这可以通过 C2 和 C-2 中的 1 以及 C1 和 C-1 中的 2 来完成，然后玩角度。",
    "Cost ": "成本 ",
    "Automatically buy C2 each tick": "每 tick 自动购买 C2",
    "Automatically buys C-10 each tick": "每 tick 自动购买 C-10",
    "Each skill costs 1 nullifier": "每个技能消耗 1 个无效符",
    "6 feet under": "6英尺以下",
    "6 feet under (last achievement) requires you to get 6 C0.": "6 英尺以下（最后一个成就）需要你获得 6 个 C0。",
    "Lowering C0": "降低 C0",
    "Legally Compromised Mechanism (have e2520 NP)": "法律上妥协的机制（有 e2520 NP）",
    "Lemniscate!": "双线形！",
    "Low Calculation Master (have e2520 DP)": "低计算主站（有 e2520 DP）",
    "Lucky Seven": "幸运七",
    "Makes C1 multiplier better but locks C1 at an angle of pi(1/2+1)": "使 C1 乘数更好，但将 C1 锁定在 pi(1/2+1) 的角度",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "LEET": "LEET",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Unlock : ": "解锁 : ",
    "Have ": "拥有 ",
    "Drawing points (DP) : ": "绘图点 (DP) :",
    "Cost : ": "成本 : ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    " Achievement Multiplier": " 成就乘数",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^拥有 (.+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+) DP$/,
    /^([\d\.]+) NP$/,
    /^([\d\.]+)NP$/,
    /^([\d\.]+)e\+([\d\.]+)DP$/,
    /^([\d\.]+)e\+([\d\.]+)NP$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\-([\d\.,]+)itπ$/,
    /^([\d\.,]+) C([\d\.,]+)$/,
    /^([\d\.,]+) C\-([\d\.,]+)$/,
    /^C\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) DP$/,
    /^([\d\.]+)e([\d\.,]+) NP$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^解锁 : (.+)$/,
    /^成本 : (.+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^-63% C7 and C-7 cost scaling (applies retroactively)$/, '$1 和 $2 成本比例（追溯适用）'],
    [/^Buys (.+) each tick$/, '每 tick 购买 $1'],
    [/^Autobuys (.+) once each tick$/, '每 tick 自购买 $1 一次'],
    [/^Buy 1 (.+) each tick$/, '每 tick 购买1个 $1'],
    [/^(.+) and (.+) cost scaling \(applies retroactively\)$/, '$1 和 $2 成本缩放（追溯适用）'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^(.+) and (.+) synergize$/, '$1 和 $2 协同化'],
    [/^Increase (.+) multiplier but locks its angle at (.+)$/, '增加 $1 乘数，但将其角度锁定在 $2'],
    [/^Increase (.+) Multiplier but locks its angle at (.+)$/, '增加 $1 乘数，但将其角度锁定在 $2'],
    [/^Increase (.+) power but locks its angle at (.+)$/, '增加 $1 力量，但将其角度锁定在 $2'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^increase C([\d\.]+)$/, '提升 C$1'],
    [/^increase C([\d\.]+) multiplier but locks its angle at (.+)$/, '提升 C$1 乘数，但将其角度锁定在 $2'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^increase C\-([\d\.,]+)$/, '提升 C\-$1'],
    [/^increase C\-([\d\.,]+) multiplier but locks its angle at (.+)$/, '提升 C\-$1 乘数，但将其角度锁定在 $2'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Cost : (.+) DP$/, '成本：$1 DP'],
    [/^Cost : ([\d\.]+)e\+([\d\.,]+)DP$/, '成本：$1e\+$2DP'],
    [/^Cost : (.+) NP$/, '成本：$1 NP'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);